name: Build
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - run: bundle install
      - name: Lint
        run: |
          gem install rubocop -v 1.50.2
          gem install rubocop-rspec -v 2.20.0
          rubocop

  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '1.9.3'
          - '2.3.0'
          - '2.5'
          - '3.2.2'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: gem install bundler -v 2
      - run: bundle install
      - name: Test
        run: bundle exec rspec
