name: Documentation
on:
  push:
    branches:
      - main
      - lint

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Generate docs
        run: |
          gem install yard
          yard doc 'lib/**/*.rb'
          cp badge.svg doc/badge.svg

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          publish_dir: doc
